spring:
  messages:
    basename: i18n/messages
  main:
    allow-circular-references: true

exam:
  file-path: data/questions.csv
  num-of-correct-answers-to-pass-exam: 3

app:
  settings:
    lang: en