spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
      data-locations: sql/data.sql
      schema-locations: sql/schema.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true