INSERT INTO GENRES (ID, `NAME`) VALUES (0, 'Роман-эпопея');
INSERT INTO AUTHORS (ID, `NAME`) VALUES (0, 'Михаил Шолохов');
INSERT INTO BOOKS (ID, TITLE, AUTHOR_ID, GENRE_ID) VALUES (0, 'Тихий Дон', 0, 0);

INSERT INTO GENRES (ID, `NAME`) VALUES (1, 'Роман');
INSERT INTO AUTHORS (ID, `NAME`) VALUES (1, 'Михаил Булгаков');
INSERT INTO BOOKS (ID, TITLE, AUTHOR_ID, GENRE_ID) VALUES (1, 'Мастер и Маргарита', 1, 1);

